#Class Mapping Resources
/ajax.do=kr.ac.kyonggi.cs.handler.action.main.AjaxAction
/information.do=kr.ac.kyonggi.cs.handler.action.main.menu.InformationAction
/notice_article_list.do=kr.ac.kyonggi.cs.handler.action.notice_boards.NoticeBoardsAction
/notice_article_reader.do=kr.ac.kyonggi.cs.handler.action.notice_boards.NoticeBoardsReaderAction
/notice_article_writer.do=kr.ac.kyonggi.cs.handler.action.notice_boards.NoticeBoardsWriterAction
/notice_article_modifier.do=kr.ac.kyonggi.cs.handler.action.notice_boards.NoticeBoardsModifierAction
/notice_board_file_delete.do=kr.ac.kyonggi.cs.handler.action.notice_boards.NoticeBoardsFileDeleteAction
/notice_board_file_upload_delete.do=kr.ac.kyonggi.cs.handler.action.notice_boards.NoticeBoardsFileUploadDeleteAction

#test
/header.do=kr.ac.kyonggi.cs .handler.action.main.HeaderAction
/download.do= kr.ac.kyonggi.cs.handler.action.graduation.GraduationDownloadActionTest


/upload.do=kr.ac.kyonggi.cs.handler.action.graduation.GraduationUploadAction
/sitemap.do=kr.ac.kyonggi.cs.handler.action.main.menu.SiteMapAction
/location.do=kr.ac.kyonggi.cs.handler.action.main.menu.LocationAction
/loginpage.do=kr.ac.kyonggi.cs.handler.action.main.menu.LoginPageAction
/login.do=kr.ac.kyonggi.cs.handler.action.main.menu.LoginAction
/logout.do=kr.ac.kyonggi.cs.handler.action.main.menu.LogoutAction
/community_club.do=kr.ac.kyonggi.cs.handler.action.community.ClubAction
/professor.do=kr.ac.kyonggi.cs.handler.action.main.menu.ProfessorAction
/laboratory.do=kr.ac.kyonggi.cs.handler.action.main.menu.LaboratoryAction
/register.do=kr.ac.kyonggi.cs.handler.action.main.menu.RegisterAction
/goChangePassword.do=kr.ac.kyonggi.cs.handler.action.main.menu.GoChangePasswordAction
/changePassword.do=kr.ac.kyonggi.cs.handler.action.main.menu.ChangePasswordAction
/goMyPage.do=kr.ac.kyonggi.cs.handler.action.main.menu.GoMyPageAction
/changeProImage.do=kr.ac.kyonggi.cs.handler.action.upload.ChangeProImageAction
/changeLabImage.do=kr.ac.kyonggi.cs.handler.action.upload.ChangeLabImageAction
/insertPro.do=kr.ac.kyonggi.cs.handler.action.upload.InsertProAction
/deletePro.do=kr.ac.kyonggi.cs.handler.action.main.menu.ProfessorDeleteAction
/insertLab.do=kr.ac.kyonggi.cs.handler.action.upload.InsertLabAction
/deleteLab.do=kr.ac.kyonggi.cs.handler.action.main.menu.LaboratoryDeleteAction
/notice_board_upload.do=kr.ac.kyonggi.cs.handler.action.upload.NoticeInsertBoardFileAction
/ajaxuser.do=kr.ac.kyonggi.cs.handler.action.main.AjaxuserAction
/admin.do=kr.ac.kyonggi.cs.handler.action.main.menu.AdminAction
/notice_download.do=kr.ac.kyonggi.cs.handler.action.notice_boards.NoticeBoardsDownloadAction
/notice_boarddelete.do=kr.ac.kyonggi.cs.handler.action.notice_boards.NoticeBoardsDeleteAction
/excel.do=kr.ac.kyonggi.cs.handler.action.upload.ExcelAction
/req_article_list.do=kr.ac.kyonggi.cs.handler.action.req_boards.req_BoardsAction
/req_article_reader.do=kr.ac.kyonggi.cs.handler.action.req_boards.req_BoardsReaderAction
/req_article_writer.do=kr.ac.kyonggi.cs.handler.action.req_boards.req_BoardsWriterAction
/req_article_modifier.do=kr.ac.kyonggi.cs.handler.action.req_boards.req_BoardsModifierAction
/req_board_excel.do=kr.ac.kyonggi.cs.handler.action.req_boards.req_BoardsExcelAction
/req_board_answer_upload.do=kr.ac.kyonggi.cs.handler.action.req_boards.req_BoardsAnswerUploadAction
/req_board_download.do=kr.ac.kyonggi.cs.handler.action.req_boards.req_BoardsDownloadAction
/req_board_all_download.do=kr.ac.kyonggi.cs.handler.action.req_boards.req_BoardsAllDownloadAction
/req_writer_upload_file.do=kr.ac.kyonggi.cs.handler.action.req_boards.req_BoardsWriterFileUploadAction
/req_writer_delete_file.do=kr.ac.kyonggi.cs.handler.action.req_boards.req_BoardsWriterFileDeleteAction
/req_writer_exit_file.do=kr.ac.kyonggi.cs.handler.action.req_boards.req_BoardsWriterExitFileAction
/req_writer_download_file.do=kr.ac.kyonggi.cs.handler.action.req_boards.req_BoardsWriterFileDownloadAction

/gallery_board_list.do=kr.ac.kyonggi.cs.handler.action.gallery_boards.GalleryBoardsAction
/gallery_board_writer.do=kr.ac.kyonggi.cs.handler.action.gallery_boards.GalleryWriterAction
/gallery_upload_image.do=kr.ac.kyonggi.cs.handler.action.gallery_boards.GalleryUploadAction
/gallery_image_delete.do=kr.ac.kyonggi.cs.handler.action.gallery_boards.GalleryImageDeleteAction
/gallery_board_reader.do=kr.ac.kyonggi.cs.handler.action.gallery_boards.GalleryReaderAction
/gallery_board_delete.do=kr.ac.kyonggi.cs.handler.action.gallery_boards.GalleryBoardsDeleteAction
/gallery_board_modify.do=kr.ac.kyonggi.cs.handler.action.gallery_boards.GalleryBoardsModifyAction
/webzine_list.do=kr.ac.kyonggi.cs.handler.action.webzine_boards.WebzineBoardsAction
/webzine_reader.do=kr.ac.kyonggi.cs.handler.action.webzine_boards.WebzineReaderAction
/webzine_writer.do=kr.ac.kyonggi.cs.handler.action.webzine_boards.WebzineWriterAction
/webzine_modifier.do=kr.ac.kyonggi.cs.handler.action.webzine_boards.WebzineModifierAction
/webzine_file_delete.do=kr.ac.kyonggi.cs.handler.action.webzine_boards.WebzineFileDeleteAction
/webzine_file_upload_delete.do=kr.ac.kyonggi.cs.handler.action.webzine_boards.WebzineFileUploadDeleteAction
/webzine_upload.do=kr.ac.kyonggi.cs.handler.action.upload.WebzineInsertBoardFileAction
/webzine_download.do=kr.ac.kyonggi.cs.handler.action.webzine_boards.WebzineDownloadAction
/webzine_boarddelete.do=kr.ac.kyonggi.cs.handler.action.webzine_boards.WebzineDeleteAction

#test
/graduation_intro.do=kr.ac.kyonggi.cs.handler.action.graduation.GraduationIntroActionTest
/form_request_test.do=kr.ac.kyonggi.cs.handler.action.graduation.GraduationFormRequestAction

/graduation_schedule.do=kr.ac.kyonggi.cs.handler.action.graduation.GraduationscheduleAction
/graduation_admin.do=kr.ac.kyonggi.cs.handler.action.graduation.GraduationAdminActionTest

/graduation_manage.do=kr.ac.kyonggi.cs.handler.action.graduation.GraduationManageUserActionTest
/graduation_form.do=kr.ac.kyonggi.cs.handler.action.graduation.GraduationActionController
/graduation_list.do=kr.ac.kyonggi.cs.handler.action.graduation.GraduationListActionTest
/curriculum.do=kr.ac.kyonggi.cs.handler.action.main.menu.CurriculumAction
/slider_upload.do=kr.ac.kyonggi.cs.handler.action.upload.SliderUploadAction

/madeby.do=kr.ac.kyonggi.cs.handler.action.main.menu.MadeByAction
/goWhatIDo.do=kr.ac.kyonggi.cs.handler.action.main.menu.GoWhatIDoPageAction
/graduation_backup.do=kr.ac.kyonggi.cs.handler.action.graduation.GraduationBackUpAction
#For Users

#jonghun(etc)
/graduation_etc_form.do=kr.ac.kyonggi.cs.handler.action.graduation.GraduationEtcFormController

/graduationexcel.do=kr.ac.kyonggi.cs.handler.action.graduation.GraduationExcelAction
/graduationexcel_req.do=kr.ac.kyonggi.cs.handler.action.graduation.GraduationExcelReqAction

/graduationExcelDown.do=kr.ac.kyonggi.cs.handler.action.graduation.GraduationExcelDownAction
/graduationReqExcelDown.do=kr.ac.kyonggi.cs.handler.action.graduation.GraduationReqExcelDownAction
/insertExcel.do=kr.ac.kyonggi.cs.handler.action.upload.InsertExcelAction

#190724(graduate backup)
/graduate_list.do=kr.ac.kyonggi.cs.handler.action.graduationBack.GraduateListAction
/graduate_back_ajax.do=kr.ac.kyonggi.cs.handler.action.graduationBack.GraduateAjaxAction
/graduation_back_info.do=kr.ac.kyonggi.cs.handler.action.graduationBack.GraduateInfoController
/graduate_excel_down.do=kr.ac.kyonggi.cs.handler.action.graduationBack.GraduateExcelDownAction
/graduate_backup.do=kr.ac.kyonggi.cs.handler.action.graduationBack.GraduateBackupAction
/graduate_backup_ajax.do=kr.ac.kyonggi.cs.handler.action.graduationBack.GraduationBackupAjaxAction
/download_back.do=kr.ac.kyonggi.cs.handler.action.graduationBack.GraduateDownloadBack
/graduate_myinfo.do=kr.ac.kyonggi.cs.handler.action.graduationBack.GraduateMyInfoAction


/mytrack.do=kr.ac.kyonggi.cs.handler.action.track.MyTrackAction
/mytrack_semester.do=kr.ac.kyonggi.cs.handler.action.track.SemesterAction
/mytrack_enroll_popup.do=kr.ac.kyonggi.cs.handler.action.track.EnrollPopupAction
/course_view.do=kr.ac.kyonggi.cs.handler.action.track.CourseViewAction
/track_view.do=kr.ac.kyonggi.cs.handler.action.track.TrackViewAction

#LockerUpdate
/locker_schedule.do=kr.ac.kyonggi.cs.handler.action.locker.LockerScheduleAction
/locker_apply.do=kr.ac.kyonggi.cs.handler.action.locker.LockerMainAction
/locker_apply_form.do=kr.ac.kyonggi.cs.handler.action.locker.LockerApplyFormAction
/locker_return.do=kr.ac.kyonggi.cs.handler.action.locker.LockerReturnAction
/locker_return2.do=kr.ac.kyonggi.cs.handler.action.locker.LockerReturnAction2
/locker_apply_list.do=kr.ac.kyonggi.cs.handler.action.locker.LockerApplyListAction
/locker_assigned_list.do=kr.ac.kyonggi.cs.handler.action.locker.LockerAssignedListAction
/locker_upload.do=kr.ac.kyonggi.cs.handler.action.locker.LockerFileUploadAction
/locker_upload2.do=kr.ac.kyonggi.cs.handler.action.locker.LockerFileUploadAction2
/locker_image.do=kr.ac.kyonggi.cs.handler.action.locker.LockerReturnImageAction
/locker_manager.do=kr.ac.kyonggi.cs.handler.action.locker.LockerManagerAction

##############################V2 URL START################################

#COMMON
/ajax.kgu=kr.ac.kyonggi.cs.v2.handler.action.AjaxAction
/ajaxuser.kgu=kr.ac.kyonggi.cs.handler.action.main.AjaxuserAction
/excel.kgu=kr.ac.kyonggi.cs.v2.handler.action.upload.ExcelAction
/insertExcel.kgu=kr.ac.kyonggi.cs.v2.handler.action.upload.InsertExcelAction

#GraduationCheckingSystem
/graduation_checking_system.kgu=kr.ac.kyonggi.cs.v2.handler.action.graduation_checking_system.GraduationCheckingSystemAction

#PAGE
/information.kgu=kr.ac.kyonggi.cs.v2.handler.action.main.menu.InformationAction
/curriculum.kgu=kr.ac.kyonggi.cs.v2.handler.action.main.menu.CurriculumAction
/location.kgu=kr.ac.kyonggi.cs.v2.handler.action.main.etc.LocationAction
/sitemap.kgu=kr.ac.kyonggi.cs.v2.handler.action.main.etc.SiteMapAction
/madeby.kgu=kr.ac.kyonggi.cs.v2.handler.action.main.etc.MadeByAction
/laboratory.kgu=kr.ac.kyonggi.cs.v2.handler.action.main.menu.LaboratoryAction
/changeLabImage.kgu=kr.ac.kyonggi.cs.v2.handler.action.upload.ChangeLabImageAction
/insertLab.kgu=kr.ac.kyonggi.cs.v2.handler.action.upload.InsertLabAction
/deleteLab.kgu=kr.ac.kyonggi.cs.v2.handler.action.main.menu.LaboratoryDeleteAction
/professor.kgu=kr.ac.kyonggi.cs.v2.handler.action.main.menu.ProfessorAction
/community_club.kgu=kr.ac.kyonggi.cs.v2.handler.action.main.menu.ClubAction
/notice_article_list.kgu=kr.ac.kyonggi.cs.v2.handler.action.notice_article.NoticeArticleAction
/notice_article_reader.kgu=kr.ac.kyonggi.cs.v2.handler.action.notice_article.NoticeArticleReaderAction
/notice_article_writer.kgu=kr.ac.kyonggi.cs.v2.handler.action.notice_article.NoticeArticleWriterAction
/notice_article_modifier.kgu=kr.ac.kyonggi.cs.v2.handler.action.notice_article.NoticeArticleModifierAction
/notice_board_file_delete.kgu=kr.ac.kyonggi.cs.v2.handler.action.notice_article.NoticeArticleFileDeleteAction
/notice_board_file_upload_delete.kgu=kr.ac.kyonggi.cs.v2.handler.action.notice_article.NoticeArticleFileUploadDeleteAction
/notice_download.kgu=kr.ac.kyonggi.cs.v2.handler.action.notice_article.NoticeArticleDownloadAction
/notice_boarddelete.kgu=kr.ac.kyonggi.cs.v2.handler.action.notice_article.NoticeArticleDeleteAction
/notice_board_upload.kgu=kr.ac.kyonggi.cs.v2.handler.action.upload.NoticeInsertBoardFileAction

/req_article_list.kgu=kr.ac.kyonggi.cs.v2.handler.action.request_boards.req_BoardsAction
/req_article_writer.kgu=kr.ac.kyonggi.cs.v2.handler.action.request_boards.req_BoardsWriterAction
/req_article_reader.kgu=kr.ac.kyonggi.cs.v2.handler.action.request_boards.req_BoardsReaderAction
/req_article_modifier.kgu=kr.ac.kyonggi.cs.v2.handler.action.request_boards.req_BoardsModifierAction

/gallery_board_list.kgu=kr.ac.kyonggi.cs.v2.handler.action.gallery_boards.GalleryBoardsAction
/gallery_board_writer.kgu=kr.ac.kyonggi.cs.v2.handler.action.gallery_boards.GalleryWriterAction
/gallery_upload_image.kgu=kr.ac.kyonggi.cs.v2.handler.action.gallery_boards.GalleryUploadAction
/gallery_image_delete.kgu=kr.ac.kyonggi.cs.v2.handler.action.gallery_boards.GalleryImageDeleteAction
/gallery_board_reader.kgu=kr.ac.kyonggi.cs.v2.handler.action.gallery_boards.GalleryReaderAction
/gallery_board_delete.kgu=kr.ac.kyonggi.cs.v2.handler.action.gallery_boards.GalleryBoardsDeleteAction
/gallery_board_modify.kgu=kr.ac.kyonggi.cs.v2.handler.action.gallery_boards.GalleryBoardsModifyAction

/webzine_list.kgu=kr.ac.kyonggi.cs.v2.handler.action.webzine_boards.WebzineBoardsAction
/webzine_reader.kgu=kr.ac.kyonggi.cs.v2.handler.action.webzine_boards.WebzineReaderAction
/webzine_writer.kgu=kr.ac.kyonggi.cs.v2.handler.action.webzine_boards.WebzineWriterAction
/webzine_modifier.kgu=kr.ac.kyonggi.cs.v2.handler.action.webzine_boards.WebzineModifierAction
/webzine_file_delete.kgu=kr.ac.kyonggi.cs.v2.handler.action.webzine_boards.WebzineFileDeleteAction
/webzine_file_upload_delete.kgu=kr.ac.kyonggi.cs.v2.handler.action.webzine_boards.WebzineFileUploadDeleteAction
/webzine_upload.kgu=kr.ac.kyonggi.cs.v2.handler.action.upload.WebzineInsertBoardFileAction
/webzine_download.kgu=kr.ac.kyonggi.cs.v2.handler.action.webzine_boards.WebzineDownloadAction
/webzine_boarddelete.kgu=kr.ac.kyonggi.cs.v2.handler.action.webzine_boards.WebzineDeleteAction


#admin
/admin.kgu=kr.ac.kyonggi.cs.v2.handler.action.main.menu.AdminAction
/slider_upload.kgu=kr.ac.kyonggi.cs.v2.handler.action.upload.SliderUploadAction

#FILE MANAGEMENT
/upload.kgu = kr.ac.kyonggi.cs.v2.handler.action.file.UploadAction
/download.kgu =kr.ac.kyonggi.cs.v2.handler.action.file.DownloadAction
/image_viewer.kgu = kr.ac.kyonggi.cs.v2.handler.action.file.ImageViewerAction
/delete.kgu = kr.ac.kyonggi.cs.v2.handler.action.file.DeleteAction

#locker
/locker_schedule.kgu=kr.ac.kyonggi.cs.v2.handler.action.locker.LockerScheduleAction
/locker_apply.kgu=kr.ac.kyonggi.cs.v2.handler.action.locker.LockerMainAction
/locker_apply_form.kgu=kr.ac.kyonggi.cs.v2.handler.action.locker.LockerApplyFormAction
/locker_return.kgu=kr.ac.kyonggi.cs.v2.handler.action.locker.LockerReturnAction
/locker_return2.kgu=kr.ac.kyonggi.cs.v2.handler.action.locker.LockerReturnAction2
/locker_apply_list.kgu=kr.ac.kyonggi.cs.v2.handler.action.locker.LockerApplyListAction
/locker_assigned_list.kgu=kr.ac.kyonggi.cs.v2.handler.action.locker.LockerAssignedListAction
/locker_upload.kgu=kr.ac.kyonggi.cs.v2.handler.action.locker.LockerFileUploadAction
/locker_upload2.kgu=kr.ac.kyonggi.cs.v2.handler.action.locker.LockerFileUploadAction2
/locker_image.kgu=kr.ac.kyonggi.cs.v2.handler.action.locker.LockerReturnImageAction
/locker_manager_list.kgu=kr.ac.kyonggi.cs.v2.handler.action.locker.LockerManagerAction